config/routes.rb
Rails.application.routes.draw do
  resources :pins

  devise_for :users
  root :to => 'pins#index'

  get 'about' => 'pages#about'

  get "contact" => "pages#contact"

end

app/models/pin.rb
class Pin < ActiveRecord::Base

	validates :description, presence: true
  validates :user_id, presence: true
	belongs_to :user

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	validates :image, presence: true
  validates :description, presence: true
	

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable,
          :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for users model
  # attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accesible :title, :body

  has_many :pins, :dependent => :destroy
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

 # def configure_permitted_parameters
  #  devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
  #  devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :current_password, :password, :password_confirmation) }
 # end
#end 

def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact 
	end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 8)
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find_by(id: params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<div class="container">
		<div class="row">
			<div class="col-md-6">
				<small>
				<%= link_to "One Month Rails", "http://onemonthrails.com" %>
				by <%= link_to "PegasusTeam", "http://pegasusteam.com" %> &copy; 2015 
				</small>
			</div>
			<div class="col-md-6">
				<p class="navbar-right">
	      	<%= link_to 'About',  about_path %> | <%= link_to 'Contact',  contact_path %>
	      </p>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'My OmRails App', root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home',  root_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to new_pin_path do %><span class="glyphicon glyphicon-plus"></span> New Pin
          <% end %> </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li><a href="#">My Profile</a></li>
            </ul>
          </li>
           <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>My Omrails</title>
	  <%= stylesheet_link_tag    'application', media: 'all' %> <!--, 'data-turbolinks-track' => true -->
	  <%= javascript_include_tag 'application' %> <!--, 'data-turbolinks-track' => true -->
		<%= csrf_meta_tags %>
	  <%= tag :meta, name: "viewport", content: "width=device-width, initial-scale=1.0" %>
	</head>
	<body>
		<%= render 'layouts/header' %>
	<div class="container">

			<% flash.each do |name, msg| %>
                <%= content_tag(:div, msg, class: "alert alert-warning") %>
            <% end %>

			<%= yield %>

			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
  <h1>Welcome to my app!</h1>
  <p>
    <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
  </p>

</div>

app/views/pages/about.html.erb
<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">
      	<h1>About my first web app!</h1>
      </div>
      <div class="panel-body">
				<p>Soon to be the home of ... something lol</p>
			</div>
		</div>
	</div>
</div>

app/views/pages/contact.html.erb
<div class="row">
  <div class="col-md-offset-3 col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
		    <h1>Contact Us</h1>
		  </div>
		  <div class="panel-body">
				<p>Contact form will go here</p>
			</div>
		</div>
	</div>
</div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>

              <% if @pin.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

                  <ul>
                    <% @pin.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
              <% end %>
                  </ul>
                </div>
              <% end %>

              <div class="form-group">
                <%= f.label :image %>
                <%= f.file_field :image, class: "form-control" %>
              </div>

              <div class="form-group">
                <%= f.label :description %>
                <%= f.text_field :description, class: "form-control" %>
              </div>
              <div class="form-group">
                <%= f.submit class: "btn btn-primary" %>
              </div>
  <% end %>
  

app/views/pins/_pin.html.erb
<tr>
  <td><%= pin.description %></td>
  <td><%= link_to 'Show', pin %></td>
  <% if current_user == pin.user %>
  	<td><a href="#"><%= pin.user.name if pin.user %></a></td>
	  <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
	  <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<% end %>
</tr>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to '&laquo; Back' .html_safe, pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box">
      <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div style="margin-top: 12px;">
        <p><strong><%= pin.user.name if pin.user %></strong><br />
        <%= pin.description %></p>
        <% if pin.user == current_user %>
          <div class="actions">
            <%= link_to edit_pin_path(pin) do %><span class="glyphicon glyphicon-edit"></span> Edit
            <% end %>
            <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %> <span class="glyphicon glyphicon-trash"></span> Delete <% end %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class="center">
   <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<%= link_to '&laquo; Back' .html_safe, pins_path %>
<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">
      	<h1>New pin</h1>
      	</div>
      	<div class="panel-body">
					<%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/pins/show.html.erb
<%= link_to '&laquo; Back' .html_safe, pins_path %>

<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <%= image_tag @pin.image.url(:medium) %>
      </div>
      <div class="panel-body">
        <p><strong><%= @pin.user.name if @pin.user %></strong></p>
        <p><%= @pin.description %></p>

        <% if @pin.user == current_user %>
          <%= link_to edit_pin_path(@pin) do %><span class="glyphicon glyphicon-edit"></span> Edit
            <% end %>
          <%= link_to @pin, method: :delete, data: { confirm: 'Are you sure?' } do %> <span class="glyphicon glyphicon-trash"></span> Delete 
          <% end %>
        <% end %>

      </div>
    </div>
  </div>
</div>